jenkins_home: "{{ COMMON_DATA_DIR }}/jenkins"
jenkins_user: "jenkins"
jenkins_group: "edx"
jenkins_server_name: "build.testeng.edx.org"
jenkins_port: 8080

jenkins_version: 1.594
jenkins_deb_url: "http://pkg.jenkins-ci.org/debian/binary/jenkins_{{ jenkins_version }}_all.deb"
jenkins_deb: "jenkins_{{ jenkins_version }}_all.deb"

jenkins_plugins:
# Legacy
    # - { name: "build-name-setter", version: "1.3" }
    # - { name: "build-pipeline-plugin", version: "1.4" }
    # - { name: "cloudbees-folder", version: "4.6.1" }
    # - { name: "copyartifact", version: "1.28" }
    # - { name: "copy-to-slave", version: "1.4.3" }
    # - { name: "dashboard-view", version: "2.9.1" }
    # - { name: "htmlpublisher", version: "1.2" }
    # - { name: "jobConfigHistory", version: "2.4" }
    # - { name: "jquery", version: "1.7.2-1" }
    # - { name: "mailer", version: "1.5" }
    # - { name: "nested-view", version: "1.10" }
    # - { name: "next-build-number", version: "1.0" }
    # - { name: "notification", version: "1.5" }
    # - { name: "pam-auth", version: "1.0" }
    # - { name: "parameterized-trigger", version: "2.20" }
    # - { name: "postbuild-task", version: "1.8" }
    # - { name: "PrioritySorter", version: "2.8" }
    # - { name: "sauce-ondemand", version: "1.61" }
    # - { name: "s3", version: "0.6" }
    # - { name: "shiningpanda", version: "0.20" }
    # - { name: "tmpcleaner", version: "1.1" }
    # - { name: "translation", version: "1.10" }
    # - { name: "violations", version: "0.7.11" }
    # - { name: "multiple-scms", version: "0.2" }
# Come with Core AFAIK
    # Ant plugin -y
    # Cvs plugin -y
    # External monitor job type plugin -y
    # javadoc     - { name: "javadoc", version: "1.1" }-y
    # - { name: "credentials", version: "1.8.3" }-y
    # junit, ldap, mailer-y
    # Matrix Project Plugin-y
    # Maven Integration Plugin-y
    # Pam Authentication-y
    # Scm API xxxxxx
    # Subversion -y
    # Translation Assistance -y
    # Windows Slaves -y
    # Matrix Authorization Strategy Plugin
# New or Active
    - { name: "ansicolor", version: "0.4.1" }
    - { name: "antisamy-markup-formatter", version: "1.3" }
    - { name: "build-timeout", version: "1.14" }
    - { name: "build-flow-plugin", version: "0.17" }
    - { name: "cobertura", version: "1.9.6" }
    - { name: "ec2", version: "1.24" }
    - { name: "git", version: "2.3.2" }
    - { name: "git-client", version: "1.13.0" }
    - { name: "github", version: "1.10" }
    - { name: "github-api", version: "1.59" }
    - { name: "github-oauth", version: "0.20" }
    - { name: "ghprb", version: "1.16-6" }
    - { name: "groovy-postbuild", version: "2.2" }
    - { name: "mapdb-api", version: "1.0.6.0"} # used by subversion plugin
    - { name: "node-iterator-api", version: "1.5" }
    - { name: "parameterized-trigger", version: "2.25" }
    - { name: "ssh-agent", version: "1.5" }
    - { name: "ssh-credentials", version: "1.10" }
    - { name: "ssh-slaves", version: "1.9" }
    - { name: "thinBackup", version: "1.7.4" }
    - { name: "token-macro", version: "1.10" }
    - { name: "timestamper", version: "1.5.7" }
    - { name: "xunit", version: "1.93" }
# Unknown
    # MapDB API Plugin
    # Script Security Plugin

jenkins_debian_pkgs:
    - openjdk-7-jdk
    - nginx
    - git
    - maven
    - daemon
    - python-pycurl

# Extra packages need for a specific jenkins instance.
JENKINS_EXTRA_PKGS: []
