- hosts: all 
  sudo: True
  gather_facts: True
  roles:
    - common
    - oraclejdk
    - elasticsearch
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC

