- name: Setup Site and Site Configurations for Otto
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - "roles/common_vars/defaults/main.yml"
    - "roles/edxapp/defaults/main.yml"
    - "roles/insights/defaults/main.yml"
    - "roles/ecommerce/defaults/main.yml"
    - "roles/programs/defaults/main.yml"
    - "roles/credentials/defaults/main.yml"
  roles:
    - otto_multitenant_setup
