---

# Example configuration for multi-server community installs of mysql (and memcached)

- name: Deploy MySQL
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
  - roles/edxlocal/defaults/main.yml
  - roles/edxapp/defaults/main.yml
  - roles/xqueue/defaults/main.yml
  - roles/analytics_api/defaults/main.yml
  roles:
  - mysql
  - edxlocal

- name: Configure MySQL
  hosts: all
  sudo: True
  vars_files:
  - roles/edxlocal/defaults/main.yml
  - roles/edxapp/defaults/main.yml
  - roles/xqueue/defaults/main.yml
  - roles/analytics_api/defaults/main.yml
  tasks:
  - name: Update MySQL bind address
    lineinfile:
      dest: /etc/mysql/my.cnf
      regexp: '^bind-address'
      state: absent
  - name: Restart MySQL
    service: name=mysql state=restarted

- name: Configure Memcached
  hosts: all
  sudo: True
  tasks:
  - name: Update Memcached bind address
    lineinfile:
      dest: /etc/memcached.conf
      regexp: '^-l 127.0.0.1'
      state: absent
  - name: Restart Memcached
    service: name=memcached state=restarted